// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TaskManageApp.DAL;

#nullable disable

namespace TaskManageApp.DAL.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TaskManageApp.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Color = "#3b82f6",
                            CreatedDate = new DateTime(2025, 3, 6, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Planning and documentation tasks",
                            IsActive = true,
                            Name = "Planning"
                        },
                        new
                        {
                            Id = 2,
                            Color = "#10b981",
                            CreatedDate = new DateTime(2025, 3, 6, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Implementation and code review work",
                            IsActive = true,
                            Name = "Development"
                        },
                        new
                        {
                            Id = 3,
                            Color = "#f59e0b",
                            CreatedDate = new DateTime(2025, 3, 6, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Infrastructure and monitoring",
                            IsActive = true,
                            Name = "Operations"
                        });
                });

            modelBuilder.Entity("TaskManageApp.Models.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsEdited")
                        .HasColumnType("bit");

                    b.Property<int>("TaskItemId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TaskItemId");

                    b.HasIndex("UserId");

                    b.ToTable("Comments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "Proposal draft looks good. Please expand the risk section.",
                            CreatedDate = new DateTime(2025, 10, 31, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            IsEdited = false,
                            TaskItemId = 1,
                            UserId = 2
                        },
                        new
                        {
                            Id = 2,
                            Content = "I pushed updates to the timeline and dependency chart.",
                            CreatedDate = new DateTime(2025, 11, 2, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            IsEdited = false,
                            TaskItemId = 1,
                            UserId = 1
                        },
                        new
                        {
                            Id = 3,
                            Content = "Please verify null-handling in authentication middleware.",
                            CreatedDate = new DateTime(2025, 11, 4, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            IsEdited = true,
                            TaskItemId = 4,
                            UserId = 3
                        },
                        new
                        {
                            Id = 4,
                            Content = "Monitoring panel draft is ready for review.",
                            CreatedDate = new DateTime(2025, 11, 5, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            IsEdited = false,
                            TaskItemId = 5,
                            UserId = 2
                        },
                        new
                        {
                            Id = 5,
                            Content = "Rate limiting thresholds need product confirmation.",
                            CreatedDate = new DateTime(2025, 11, 6, 4, 0, 0, 0, DateTimeKind.Unspecified),
                            IsEdited = false,
                            TaskItemId = 7,
                            UserId = 1
                        });
                });

            modelBuilder.Entity("TaskManageApp.Models.TaskAttachment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TaskItemId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TaskItemId");

                    b.ToTable("TaskAttachments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FileName = "project-proposal-v2.pdf",
                            FilePath = "/mock-files/project-proposal-v2.pdf",
                            TaskItemId = 1
                        },
                        new
                        {
                            Id = 2,
                            FileName = "code-review-checklist.docx",
                            FilePath = "/mock-files/code-review-checklist.docx",
                            TaskItemId = 2
                        },
                        new
                        {
                            Id = 3,
                            FileName = "monitoring-dashboard-sketch.png",
                            FilePath = "/mock-files/monitoring-dashboard-sketch.png",
                            TaskItemId = 5
                        });
                });

            modelBuilder.Entity("TaskManageApp.Models.TaskHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ActionDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("TaskItemId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TaskItemId");

                    b.ToTable("TaskHistories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Action = "Task created",
                            ActionDate = new DateTime(2025, 10, 22, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            TaskItemId = 1
                        },
                        new
                        {
                            Id = 2,
                            Action = "Priority changed to High",
                            ActionDate = new DateTime(2025, 10, 29, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            TaskItemId = 1
                        },
                        new
                        {
                            Id = 3,
                            Action = "Assigned to Marko Horvat",
                            ActionDate = new DateTime(2025, 11, 1, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            TaskItemId = 2
                        },
                        new
                        {
                            Id = 4,
                            Action = "Status changed to Completed",
                            ActionDate = new DateTime(2025, 11, 5, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            TaskItemId = 3
                        },
                        new
                        {
                            Id = 5,
                            Action = "Description updated",
                            ActionDate = new DateTime(2025, 11, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TaskItemId = 7
                        });
                });

            modelBuilder.Entity("TaskManageApp.Models.TaskItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<int>("PriorityId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("UserId");

                    b.ToTable("Tasks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2025, 10, 22, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Write and finalize the comprehensive project proposal document including scope, timeline, and budget estimates.",
                            DueDate = new DateTime(2025, 11, 4, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            IsCompleted = false,
                            PriorityId = 2,
                            Title = "Complete project proposal",
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 2,
                            CreatedDate = new DateTime(2025, 11, 1, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Review the latest code changes in the main repository branch.",
                            DueDate = new DateTime(2025, 11, 8, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            IsCompleted = false,
                            PriorityId = 2,
                            Title = "Review code changes",
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2025, 10, 27, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Update the user manual with new features released in v2.1.",
                            DueDate = new DateTime(2025, 11, 5, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            IsCompleted = true,
                            PriorityId = 1,
                            Title = "Update documentation",
                            UserId = 1
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            CreatedDate = new DateTime(2025, 11, 3, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Refactor the authentication module to improve security and performance.",
                            DueDate = new DateTime(2025, 11, 13, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            IsCompleted = false,
                            PriorityId = 1,
                            Title = "Refactor authentication module",
                            UserId = 1
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 3,
                            CreatedDate = new DateTime(2025, 11, 5, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Setup application monitoring and performance dashboard.",
                            DueDate = new DateTime(2025, 12, 6, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            IsCompleted = false,
                            PriorityId = 0,
                            Title = "Setup monitoring dashboard",
                            UserId = 2
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 2,
                            CreatedDate = new DateTime(2025, 10, 30, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Fix the issue where users cannot login with special characters in password.",
                            DueDate = new DateTime(2025, 11, 5, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            IsCompleted = true,
                            PriorityId = 2,
                            Title = "Fix login bug",
                            UserId = 2
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 2,
                            CreatedDate = new DateTime(2025, 11, 4, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Design and implement rate limiting and caching mechanisms.",
                            DueDate = new DateTime(2025, 11, 20, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            IsCompleted = false,
                            PriorityId = 1,
                            Title = "Implement comprehensive API rate limiting and caching strategy to prevent abuse while maintaining optimal performance",
                            UserId = 1
                        });
                });

            modelBuilder.Entity("TaskManageApp.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 5, 6, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ana.kovacic@example.com",
                            FirstName = "Ana",
                            LastName = "Kovacic",
                            PasswordHash = "mock-hash-1",
                            Username = "ana.kovacic"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 7, 6, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "marko.horvat@example.com",
                            FirstName = "Marko",
                            LastName = "Horvat",
                            PasswordHash = "mock-hash-2",
                            Username = "marko.horvat"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 9, 6, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "petra.babic@example.com",
                            FirstName = "Petra",
                            LastName = "Babic",
                            PasswordHash = "mock-hash-3",
                            Username = "petra.babic"
                        });
                });

            modelBuilder.Entity("TaskManageApp.Models.Comment", b =>
                {
                    b.HasOne("TaskManageApp.Models.TaskItem", "TaskItem")
                        .WithMany("Comments")
                        .HasForeignKey("TaskItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TaskManageApp.Models.User", "User")
                        .WithMany("Comments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TaskItem");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TaskManageApp.Models.TaskAttachment", b =>
                {
                    b.HasOne("TaskManageApp.Models.TaskItem", "TaskItem")
                        .WithMany()
                        .HasForeignKey("TaskItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TaskItem");
                });

            modelBuilder.Entity("TaskManageApp.Models.TaskHistory", b =>
                {
                    b.HasOne("TaskManageApp.Models.TaskItem", "TaskItem")
                        .WithMany("TaskHistories")
                        .HasForeignKey("TaskItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TaskItem");
                });

            modelBuilder.Entity("TaskManageApp.Models.TaskItem", b =>
                {
                    b.HasOne("TaskManageApp.Models.Category", "Category")
                        .WithMany("Tasks")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TaskManageApp.Models.User", "User")
                        .WithMany("Tasks")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TaskManageApp.Models.Category", b =>
                {
                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("TaskManageApp.Models.TaskItem", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("TaskHistories");
                });

            modelBuilder.Entity("TaskManageApp.Models.User", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Tasks");
                });
#pragma warning restore 612, 618
        }
    }
}
